### ISSUE TITLE
Looping sound occasionally never stops

### ISSUE THREAD

**Issue by soundasleep** [spookygames/gdx-sfx#6]
First issue, thank you for this library so far!

I'm having some weird behaviour on desktop (Windows) where, if you try to play multiple looping sounds at the same time, occasionally one of these `SfxSound` sound sometimes never stops playing, even if you store the soundID and request it to stop:

```java
// pending.sound is a SfxSound
long actualId = spatializedPlayer.play(pending.position, pending.sound, pending.pitch, pending.looping); 
// ... and later:
spatializedPlayer.stop(actualId);
// ... and even later:
spatializer.setCenter(middlePoint.x, middlePoint.y, soundZoom);
spatializedPlayer.update(deltaTime);
```

It works fine using standards sounds (`Sound`) though:

```java
// pending.sound is a Sound
long actualId;
if (pending.looping) {
	actualId = pending.sound.loop(1.0f /* vol */, pending.pitch, 0.0f /* pan */);
} else {
	actualId = pending.sound.play(1.0f /* vol */, pending.pitch, 0.0f /* pan */);
}
pending.actualId = actualId;
// ... and later:
actual.sound.stop(actual.actualId);
```

As far as I can tell it's not due to
- playing the same asset file twice
- .wav or .ogg
- not playing or updating on the render() thread
- assets not being loaded yet through AssetManager
- any concurrency/synchronized nonsense
- and I don't think it's due to issue #5 

Any ideas?

**Comment by soundasleep** [comment]
OK I did some investigation and it seems to be something with `SpatializedPlayer`.

Changing:

```
spatializedPlayer.stop(actual.actualId);
```

to:

```
actual.sound.stop(actual.actualId);   // actual.sound is a SfxSound
```

And the sounds stop perfectly and as expected.

**Comment by arthurtemple** [comment]
Thanks for the feedback.

I have a hard time reproducing the issue. Could you please provide a code sample showing bad behavior?

**Comment by soundasleep** [comment]
Sorry I haven't been able to reproduce it at the moment, I've gone with a different solution (using OpenAL: https://github.com/soundasleep/libgdx-openal-reverb-demo) and I don't experience this behaviour anymore. It might have something to do with OpenAL running out of idle sound sources (i.e. [soundId may occasionally be -1](https://github.com/soundasleep/libgdx-openal-reverb-demo/blob/main/ReverbSound.java#L103))?
